import {useEffect, useState, type FormEvent} from 'react';

export const widgetCatalog = [
  {type:'metric_workflows',label:'Workflow volume',description:'Recorded executions and step failures'},
  {type:'metric_acceptance',label:'Outcome coverage',description:'Accepted results and missing outcomes'},
  {type:'metric_unknown_cost',label:'Price coverage',description:'Priced and unknown-cost usage'},
  {type:'cost_breakdown',label:'Recorded cost',description:'Amounts separated by currency and basis'},
  {type:'usage_coverage',label:'Evidence coverage',description:'Outcome and price evidence across this report'},
  {type:'workflow_comparison',label:'Workflow comparison',description:'Compare recorded cost by run'},
  {type:'findings',label:'Investigation queue',description:'Assessment findings and their evidence'},
  {type:'workflow_list',label:'Workflow register',description:'Status, outcome and recorded cost by run'},
] as const;
export type WidgetType = typeof widgetCatalog[number]['type'];
export type DashboardWidget = {type:WidgetType,width:'half'|'full'};
export type SavedDashboard = {id:string,application_id:string,name:string,widgets:DashboardWidget[],created_at:string,updated_at:string};
export type ReportCohort = {summary:Record<string,number>,costs:{amount:string,currency:string,cost_basis:string,partial:boolean}[],workflows:{workflow_id:string,status:string,accepted:boolean|null,steps:{name:string}[],costs:{amount:string,currency:string,cost_basis:string,partial:boolean}[],usage?:unknown[],usage_events?:number,unknown_cost_events?:number}[],findings:{code:string,message:string,evidence:string[]}[]};
export const initialWidgets:DashboardWidget[] = [
  {type:'metric_workflows',width:'half'},
  {type:'metric_acceptance',width:'half'},
  {type:'usage_coverage',width:'full'},
  {type:'workflow_comparison',width:'full'},
];
const labelOf=(type:WidgetType)=>widgetCatalog.find(item=>item.type===type)?.label??type;
const count=(cohort:ReportCohort|undefined,key:string)=>cohort?.summary[key]??0;
const pct=(part:number,total:number)=>total?Math.round(part/total*100):0;

export function WidgetEditor({widgets,onChange}:{widgets:DashboardWidget[],onChange:(widgets:DashboardWidget[])=>void}){
  function move(index:number,offset:number){const next=[...widgets];[next[index],next[index+offset]]=[next[index+offset],next[index]];onChange(next);}
  return <section className="builder-editor" aria-label="Dashboard layout editor"><div className="builder-section-head"><div><span className="eyebrow">02 / COMPOSE</span><h2>Choose your evidence</h2><p>Up to eight distinct widgets. Use the arrows to set their order.</p></div><span className="builder-count">{widgets.length} / 8</span></div>
    <div className="builder-widget-list">{widgets.map((widget,index)=><div className="builder-widget-row" key={widget.type}><span className="builder-order">{String(index+1).padStart(2,'0')}</span><div className="builder-widget-name"><strong>{labelOf(widget.type)}</strong><small>{widgetCatalog.find(item=>item.type===widget.type)?.description}</small></div><label className="builder-width">Size<select aria-label={`${labelOf(widget.type)} width`} value={widget.width} onChange={event=>onChange(widgets.map((item,i)=>i===index?{...item,width:event.target.value as 'half'|'full'}:item))}><option value="half">Half</option><option value="full">Full</option></select></label><div className="builder-row-actions"><button type="button" aria-label={`Move ${labelOf(widget.type)} up`} disabled={index===0} onClick={()=>move(index,-1)}>↑</button><button type="button" aria-label={`Move ${labelOf(widget.type)} down`} disabled={index===widgets.length-1} onClick={()=>move(index,1)}>↓</button><button type="button" aria-label={`Remove ${labelOf(widget.type)}`} onClick={()=>onChange(widgets.filter((_,i)=>i!==index))}>×</button></div></div>)}</div>
    <div className="builder-gallery"><span className="eyebrow">ADD A WIDGET</span><div>{widgetCatalog.filter(item=>!widgets.some(widget=>widget.type===item.type)).map(item=><button type="button" key={item.type} disabled={widgets.length>=8} onClick={()=>onChange([...widgets,{type:item.type,width:'half'}])}><span>＋</span><strong>{item.label}</strong><small>{item.description}</small></button>)}</div>{widgets.length===8&&<p>All eight widget types are in this layout.</p>}</div>
  </section>;
}

function WidgetContent({type,cohort}:{type:WidgetType,cohort:ReportCohort|undefined}){
  if(!cohort)return <div className="builder-placeholder" aria-hidden="true"><i/><i/><i/></div>;
  const summary=cohort.summary;
  if(type==='metric_workflows')return <div className="builder-stat"><strong>{count(cohort,'workflows')}</strong><span>recorded workflows</span><p>{count(cohort,'failed_steps')} failed step{count(cohort,'failed_steps')===1?'':'s'} · {count(cohort,'retry_steps')} retr{count(cohort,'retry_steps')===1?'y':'ies'}</p></div>;
  if(type==='metric_acceptance')return <div className="builder-stat"><strong>{count(cohort,'accepted_workflows')}<small> / {count(cohort,'workflows')}</small></strong><span>accepted results</span><p>{Math.max(0,count(cohort,'workflows')-count(cohort,'outcome_workflows'))} workflow{count(cohort,'workflows')-count(cohort,'outcome_workflows')===1?'':'s'} without a recorded outcome</p></div>;
  if(type==='metric_unknown_cost')return <div className="builder-stat"><strong>{count(cohort,'unknown_cost_events')}</strong><span>usage events without a recorded price</span><p>Unknown cost does not mean zero cost.</p></div>;
  if(type==='cost_breakdown')return <div className="builder-costs">{cohort.costs.length?cohort.costs.map((cost,index)=><div key={index}><strong>{cost.amount} {cost.currency}</strong><span>{cost.cost_basis}{cost.partial?' · partial':''}</span></div>):<p>No priced usage recorded. Total cost is unknown.</p>}<p>Amounts are never combined across currencies or price bases. Unpriced usage is excluded.</p></div>;
  if(type==='usage_coverage'){
    const workflows=count(cohort,'workflows'), outcomes=count(cohort,'outcome_workflows'), priced=count(cohort,'known_cost_events'), unknown=count(cohort,'unknown_cost_events');
    return <div className="builder-coverage"><div><span><strong>Outcome evidence</strong><b>{outcomes} / {workflows}</b></span><div className="builder-track" role="img" aria-label={`${outcomes} of ${workflows} workflows have recorded outcomes`}><i style={{width:`${pct(outcomes,workflows)}%`}}/></div></div><div><span><strong>Price evidence</strong><b>{priced} / {priced+unknown}</b></span><div className="builder-track warm" role="img" aria-label={`${priced} of ${priced+unknown} usage events have recorded prices`}><i style={{width:`${pct(priced,priced+unknown)}%`}}/></div></div><p>Coverage applies only to events in the selected report window.</p></div>;
  }
  if(type==='workflow_comparison'){
    const reference=cohort.costs[0];
    if(!reference)return <p className="builder-no-data">No comparable priced usage recorded. Costs are unknown where price evidence is missing.</p>;
    const rows=cohort.workflows.map((workflow,index)=>({workflow,index,amount:workflow.costs.filter(cost=>cost.currency===reference.currency&&cost.cost_basis===reference.cost_basis).reduce((total,cost)=>total+Number(cost.amount),0)}));
    const max=Math.max(0,...rows.map(row=>row.amount))||1;
    return <div className="builder-bars">{rows.map(({workflow,index,amount})=><div className="builder-bar-row" key={workflow.workflow_id}><span title={workflow.steps[0]?.name||'Workflow'}>Run {index+1} <small>{workflow.steps[0]?.name||'Workflow'}</small></span><div className="builder-track" aria-hidden="true"><i style={{width:`${amount/max*100}%`}}/></div><b>{amount?amount.toFixed(3):'—'}</b></div>)}<p>{reference.currency} · {reference.cost_basis} basis. Bars exclude unpriced usage and other currencies or bases.</p></div>;
  }
  if(type==='findings')return <div className="builder-findings">{cohort.findings.length?cohort.findings.slice(0,5).map((finding,index)=><details key={`${finding.code}-${index}`}><summary><span>{String(index+1).padStart(2,'0')}</span><strong>{finding.code.replaceAll('_',' ')}</strong></summary><p>{finding.message}</p><small>{finding.evidence.length} evidence reference{finding.evidence.length===1?'':'s'} · Investigate before changing the application.</small></details>):<p>No assessment findings in this report window.</p>}</div>;
  return <div className="builder-table-wrap" tabIndex={0} role="region" aria-label="Workflow register, scroll horizontally for more columns"><table><thead><tr><th>Run</th><th>Status</th><th>Outcome</th><th>Recorded cost</th></tr></thead><tbody>{cohort.workflows.map((workflow,index)=><tr key={workflow.workflow_id}><td>Run {index+1}<small>{workflow.steps[0]?.name||'Missing root'}</small></td><td>{workflow.status}</td><td>{workflow.accepted===null?'Not recorded':workflow.accepted?'Accepted':'Not accepted'}</td><td>{workflow.costs.map(cost=>`${cost.amount} ${cost.currency} · ${cost.cost_basis}${cost.partial?' partial':''}`).join(', ')||'Not priced'}{(workflow.unknown_cost_events??0)>0&&<small>{workflow.unknown_cost_events} unknown cost event(s)</small>}</td></tr>)}</tbody></table></div>;
}

export function WidgetCanvas({widgets,cohort,preview=false}:{widgets:DashboardWidget[],cohort:ReportCohort|undefined,preview?:boolean}){
  return <div className={'builder-canvas'+(preview?' is-preview':'')} aria-label={preview?'Dashboard preview':'Dashboard widgets'}>{!cohort&&<p className="builder-canvas-empty">No workflows in this report window. The layout is ready; widgets will populate when telemetry arrives.</p>}{widgets.map((widget,index)=><section className={'builder-widget '+(widget.width==='full'?'full':'half')} key={widget.type}><div className="builder-widget-head"><span>{String(index+1).padStart(2,'0')} / {labelOf(widget.type)}</span><span aria-label="Report data">↗</span></div><WidgetContent type={widget.type} cohort={cohort}/></section>)}</div>;
}

type DashboardApi=<T,>(path:string,method?:string,body?:unknown)=>Promise<T>;
export function DashboardCreator({application,cohort,cohortLabel,scope,request,onManageApplications}:{application:{id:string,name:string}|undefined,cohort:ReportCohort|undefined,cohortLabel:string|undefined,scope:{since:string,until:string,truncated:boolean,returned_events:number}|undefined,request:DashboardApi,onManageApplications:()=>void}){
  const [dashboards,setDashboards]=useState<SavedDashboard[]>([]),[activeId,setActiveId]=useState(''),[name,setName]=useState(''),[widgets,setWidgets]=useState<DashboardWidget[]>(initialWidgets),[editing,setEditing]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[confirmDelete,setConfirmDelete]=useState(false);
  useEffect(()=>{if(!application)return;let alive=true;setBusy(true);setError('');request<{dashboards:SavedDashboard[]}>(`/dashboards?application_id=${encodeURIComponent(application.id)}`).then(data=>{if(alive)setDashboards(data.dashboards);}).catch(err=>{if(alive)setError((err as Error).message);}).finally(()=>{if(alive)setBusy(false);});return()=>{alive=false;};},[application?.id,request]);
  const active=dashboards.find(item=>item.id===activeId);
  function beginNew(){setActiveId('');setName('');setWidgets(initialWidgets);setEditing(true);setConfirmDelete(false);setError('');setNotice('');}
  function open(item:SavedDashboard){setActiveId(item.id);setName(item.name);setWidgets(item.widgets);setEditing(false);setConfirmDelete(false);setError('');setNotice('');}
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!application||!widgets.length)return;setBusy(true);setError('');setNotice('');try{const result=await request<{dashboard:SavedDashboard}>(active?`/dashboards/${active.id}`:'/dashboards',active?'PUT':'POST',active?{name,widgets}:{name,application_id:application.id,widgets});const saved=result.dashboard;setDashboards(current=>[...current.filter(item=>item.id!==saved.id),saved].sort((a,b)=>b.updated_at.localeCompare(a.updated_at)));setActiveId(saved.id);setName(saved.name);setWidgets(saved.widgets);setEditing(false);setNotice('Dashboard saved for this application.');}catch(err){const message=(err as Error).message;setError((message==='Failed to fetch'?'Could not reach the API. Check the connection and try saving again.':message)+' Your name and layout are still here.');}finally{setBusy(false);}}
  async function remove(){if(!active)return;setBusy(true);setError('');try{await request(`/dashboards/${active.id}`,'DELETE');setDashboards(current=>current.filter(item=>item.id!==active.id));setActiveId('');setName('');setWidgets(initialWidgets);setEditing(false);setConfirmDelete(false);setNotice('Dashboard deleted.');}catch(err){setError((err as Error).message);}finally{setBusy(false);}}
  if(!application)return <section className="builder-empty"><span className="builder-empty-mark">▦</span><h2>Select an application to build a dashboard</h2><p>Each dashboard belongs to one application. Select it above to arrange widgets using that application’s recorded data.</p><button className="button secondary" onClick={onManageApplications}>Add or manage applications →</button></section>;
  return <div className="builder-page"><div className="builder-intro"><div><span className="eyebrow">APPLICATION DASHBOARDS</span><h2>{application.name}, your way.</h2><p>Build a focused view from the evidence TraceWorth has recorded. Layouts save to your account; metrics update from the selected report window.</p></div><button className="button primary" onClick={beginNew} disabled={busy||dashboards.length>=25}>＋ New dashboard</button></div>
    <div className="builder-scope" role="status"><span className="builder-scope-dot"/><div><strong>{scope?.truncated?'Partial report · received-time limit reached':'Received-time report'}{cohortLabel?` · ${cohortLabel}`:''}</strong><p>{scope?`${new Date(scope.since).toLocaleString()} – ${new Date(scope.until).toLocaleString()} · ${scope.returned_events} events loaded across this application’s cohorts. Workflows crossing this window may be incomplete.`:'Waiting for metrics. Saved layouts remain available.'} Widgets show only the selected environment and configuration. Unknown cost stays unknown; these are not all-time totals.</p></div></div>
    {error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}
    <div className="builder-body"><aside className="builder-rail"><div className="builder-rail-head"><span className="eyebrow">01 / YOUR VIEWS</span><span>{dashboards.length} / 25</span></div>{busy&&!dashboards.length?<p>Loading dashboards…</p>:dashboards.length?<div className="builder-saved-list">{dashboards.map(item=><button type="button" key={item.id} className={activeId===item.id?'active':''} onClick={()=>open(item)}><strong>{item.name}</strong><small>{item.widgets.length} widgets · Updated {new Date(item.updated_at).toLocaleDateString()}</small></button>)}</div>:<div className="builder-rail-empty"><span>◫</span><strong>No dashboards yet</strong><p>Create your first view and choose the evidence that matters to this application.</p></div>}<p className="builder-rail-note">Only the signed-in account can open these layouts. The report itself stays scoped to the selected application.</p></aside>
      <div className="builder-stage">{editing?<><form onSubmit={save}><div className="builder-name-row"><label>Dashboard name<input value={name} onChange={event=>setName(event.target.value)} required minLength={1} maxLength={80} placeholder="e.g. Quality and cost review" autoFocus/></label><span>{active?'Edit saved dashboard':'New dashboard'}</span></div><WidgetEditor widgets={widgets} onChange={setWidgets}/><div className="builder-actions"><button className="button primary" disabled={busy||!widgets.length}>{busy?'Saving…':active?'Save changes':'Create dashboard'}</button><button type="button" className="button secondary" onClick={()=>{if(active)open(active);else setEditing(false);}}>Cancel</button><span>Layouts only · no query or application data is changed.</span></div></form><div className="builder-preview-head"><span className="eyebrow">LIVE PREVIEW</span><p>{cohort?'Using the selected application report':'Waiting for recorded telemetry'}</p></div><WidgetCanvas widgets={widgets} cohort={cohort} preview/></>:active?<><div className="builder-view-head"><div><span className="eyebrow">SAVED VIEW</span><h2>{active.name}</h2><p>{active.widgets.length} widgets · Updated {new Date(active.updated_at).toLocaleString()}</p></div><div><button className="button secondary" onClick={()=>setEditing(true)}>Edit layout</button><button className="link-button builder-delete" onClick={()=>setConfirmDelete(true)}>Delete</button></div></div>{confirmDelete&&<div className="builder-confirm" role="alert"><strong>Delete “{active.name}”?</strong><p>The layout will be removed. Recorded telemetry remains.</p><button className="button secondary" onClick={()=>setConfirmDelete(false)}>Cancel</button><button className="button primary" disabled={busy} onClick={()=>void remove()}>Confirm delete</button></div>}<WidgetCanvas widgets={active.widgets} cohort={cohort}/></>:<div className="builder-welcome"><span className="builder-welcome-art">01 <i/> 02 <i/> 03</span><span className="eyebrow">A CLEARER WAY TO REVIEW</span><h2>Start with the question,<br/>then choose the evidence.</h2><p>Combine workflow volume, outcome coverage, recorded cost, findings, and run comparisons in a view you can return to.</p><button className="button primary" onClick={beginNew} disabled={busy||dashboards.length>=25}>Create a dashboard →</button></div>}</div>
    </div>
  </div>;
}
